### ISSUE TITLE
microbit.subscribeEvents

### ISSUE THREAD

**Issue by MatthijsKamstra** [sandeepmistry/node-bbc-microbit#14]
The code for [EventListeners](https://github.com/sandeepmistry/node-bbc-microbit/blob/master/lib/event-service.js) used in the [event-listener.js](https://github.com/sandeepmistry/node-bbc-microbit/blob/master/examples/event-listener.js) doesn't work when using NPM.

I guess the code is not updated to NPM yet?

![screen shot 2017-03-28 at 09 37 58](https://cloud.githubusercontent.com/assets/907219/24393907/416030b0-139a-11e7-850b-6b0b2e856673.png)

**Comment by sandeepmistry** [comment]
I've tagged and published a new v0.2.0 release to npm. I was hoping to get feedback on the new functionality before publishing but that never happened (https://github.com/sandeepmistry/node-bbc-microbit/pull/7#issuecomment-267216084).
