### ISSUE TITLE
support for Event Service

### ISSUE THREAD

**Issue by pelikhan** [sandeepmistry/node-bbc-microbit#5]
The event service allows to send/receive custom messages from the micro:bit. It also enables all the built-in blocks like "alarm" , "remote control" etc...

https://lancaster-university.github.io/microbit-docs/ble/profile/#about-the-event-service

**Comment by sandeepmistry** [comment]
Hi @pelikhan,

Do you have time to work on a pull request for this? You can use a similar patter to the `lib/*-service.js` files.

**Comment by sandeepmistry** [comment]
Closed via #7.
